name: Build Android APK (arm64)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # ✅ Pin Gradle to 8.7 (works with AGP 8.2.2)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          target: android-33
          arch: arm64-v8a
          components: build-tools;33.0.2

      - name: Build APK
        run: gradle assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-release
          path: app/build/outputs/apk/release/*.apk
