name: Build Android APK (arm64)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Install Android SDK 34 (arm64)
      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          target: android-34
          arch: arm64-v8a
          components: build-tools;34.0.0

      # 4️⃣ Generate debug keystore for signing release APK
      - name: Generate debug keystore
        run: |
          mkdir -p $HOME/.android
          keytool -genkeypair -v \
            -keystore $HOME/.android/debug.keystore \
            -storepass android -alias androiddebugkey -keypass android \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Minimal App, OU=Dev, O=Example, L=City, ST=State, C=US"

      # 5️⃣ Install Gradle 8.7 and generate wrapper
      - name: Install Gradle and generate wrapper
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          wget https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle-8.7-bin.zip -d $HOME/gradle
          export PATH=$HOME/gradle/gradle-8.7/bin:$PATH
          gradle wrapper --gradle-version 8.7

      # 6️⃣ Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 7️⃣ Build release APK using Gradle wrapper
      - name: Build APK
        run: ./gradlew assembleRelease

      # 8️⃣ Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-release
          path: app/build/outputs/apk/release/*.apk
