name: Build Android APK (arm64)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Install Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.2

      # 4. Accept Android SDK licenses
      - name: Accept licenses
        run: yes | sdkmanager --licenses

      # 5. Build Release APK
      - name: Build APK
        run: ./gradlew assembleRelease

      # 6. Upload the built APK
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-arm64-release
          path: app/build/outputs/apk/release/*.apk
