name: Build Android APK (arm64)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up JDK 17 (required for Android Gradle Plugin 8+)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Set up Gradle (no gradlew required)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # 4. Install Android SDK & NDK (arm64 only)
      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          target: android-34
          arch: arm64-v8a
          components: build-tools;34.0.0

      # 5. Build release APK (arm64)
      - name: Build APK
        run: gradle assembleRelease

      # 6. Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-release
          path: app/build/outputs/apk/release/*.apk
