name: Build Android APK (arm64)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Install Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          target: android-34
          arch: arm64-v8a
          components: build-tools;34.0.0,platform-tools,platforms;android-34

      # 4️⃣ Generate debug keystore for signing
      - name: Generate debug keystore
        run: |
          mkdir -p $HOME/.android
          keytool -genkey -v -keystore $HOME/.android/debug.keystore \
            -storepass android -alias androiddebugkey -keypass android \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Minimal App, OU=Dev, O=Example, L=City, ST=State, C=US"

      # 5️⃣ Build release APK using Gradle wrapper
      - name: Build APK
        run: ./gradlew assembleRelease --no-daemon

      # 6️⃣ Upload the APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-release
          path: app/build/outputs/apk/release/*.apk
